config/routes.rb
Rails.application.routes.draw do
  resources :reporte_abusos
  resources :contratos
  resources :folio_abusos
  resources :abusos

  root "folio_abusos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/reporte_abuso.rb
class ReporteAbuso < ApplicationRecord
end

app/controllers/reporte_abusos_controller.rb
class ReporteAbusosController < ApplicationController
  before_action :set_reporte_abuso, only: %i[ show edit update destroy ]

  # GET /reporte_abusos or /reporte_abusos.json
  def index
    @reporte_abusos = ReporteAbuso.all
  end

  # GET /reporte_abusos/1 or /reporte_abusos/1.json
  def show
  end

  # GET /reporte_abusos/new
  def new
    @reporte_abuso = ReporteAbuso.new
  end

  # GET /reporte_abusos/1/edit
  def edit
  end

  # POST /reporte_abusos or /reporte_abusos.json
  def create
    @reporte_abuso = ReporteAbuso.new(reporte_abuso_params)

    respond_to do |format|
      if @reporte_abuso.save
        format.html { redirect_to reporte_abuso_url(@reporte_abuso), notice: "Reporte abuso was successfully created." }
        format.json { render :show, status: :created, location: @reporte_abuso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reporte_abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reporte_abusos/1 or /reporte_abusos/1.json
  def update
    respond_to do |format|
      if @reporte_abuso.update(reporte_abuso_params)
        format.html { redirect_to reporte_abuso_url(@reporte_abuso), notice: "Reporte abuso was successfully updated." }
        format.json { render :show, status: :ok, location: @reporte_abuso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reporte_abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reporte_abusos/1 or /reporte_abusos/1.json
  def destroy
    @reporte_abuso.destroy

    respond_to do |format|
      format.html { redirect_to reporte_abusos_url, notice: "Reporte abuso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reporte_abuso
      @reporte_abuso = ReporteAbuso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reporte_abuso_params
      params.require(:reporte_abuso).permit(:tipo_abuso, :descripcion)
    end
end

app/helpers/reporte_abusos_helper.rb
module ReporteAbusosHelper
end

app/views/reporte_abusos/_form.html.erb
<%= form_with(model: reporte_abuso) do |form| %>
  <% if reporte_abuso.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reporte_abuso.errors.count, "error") %> prohibited this reporte_abuso from being saved:</h2>

      <ul>
        <% reporte_abuso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tipo_abuso, style: "display: block" %>
    <%= form.text_field :tipo_abuso %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reporte_abusos/_reporte_abuso.html.erb
<div id="<%= dom_id reporte_abuso %>">
  <p>
    <strong>Tipo abuso:</strong>
    <%= reporte_abuso.tipo_abuso %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= reporte_abuso.descripcion %>
  </p>

</div>

app/views/reporte_abusos/edit.html.erb
<h1>Editing reporte abuso</h1>

<%= render "form", reporte_abuso: @reporte_abuso %>

<br>

<div>
  <%= link_to "Show this reporte abuso", @reporte_abuso %> |
  <%= link_to "Back to reporte abusos", reporte_abusos_path %>
</div>

app/views/reporte_abusos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reporte abusos</h1>

<div id="reporte_abusos">
  <% @reporte_abusos.each do |reporte_abuso| %>
    <%= render reporte_abuso %>
    <p>
      <%= link_to "Show this reporte abuso", reporte_abuso %>
    </p>
  <% end %>
</div>

<%= link_to "New reporte abuso", new_reporte_abuso_path %>

app/views/reporte_abusos/new.html.erb
<h1>New reporte abuso</h1>

<%= render "form", reporte_abuso: @reporte_abuso %>

<br>

<div>
  <%= link_to "Back to reporte abusos", reporte_abusos_path %>
</div>

app/views/reporte_abusos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reporte_abuso %>

<div>
  <%= link_to "Edit this reporte abuso", edit_reporte_abuso_path(@reporte_abuso) %> |
  <%= link_to "Back to reporte abusos", reporte_abusos_path %>

  <%= button_to "Destroy this reporte abuso", @reporte_abuso, method: :delete %>
</div>