config/routes.rb
Rails.application.routes.draw do
  resources :reporte_abusos
  resources :contratos
  resources :folio_abusos
  resources :abusos

  root "folio_abusos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/abuso.rb
class Abuso < ApplicationRecord
end

app/controllers/abusos_controller.rb
class AbusosController < ApplicationController
  before_action :set_abuso, only: %i[ show edit update destroy ]

  # GET /abusos or /abusos.json
  def index
    @abusos = Abuso.all
  end

  # GET /abusos/1 or /abusos/1.json
  def show
  end

  # GET /abusos/new
  def new
    @abuso = Abuso.new
  end

  # GET /abusos/1/edit
  def edit
  end

  # POST /abusos or /abusos.json
  def create
    @abuso = Abuso.new(abuso_params)

    respond_to do |format|
      if @abuso.save
        format.html { redirect_to abuso_url(@abuso), notice: "Abuso was successfully created." }
        format.json { render :show, status: :created, location: @abuso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abusos/1 or /abusos/1.json
  def update
    respond_to do |format|
      if @abuso.update(abuso_params)
        format.html { redirect_to abuso_url(@abuso), notice: "Abuso was successfully updated." }
        format.json { render :show, status: :ok, location: @abuso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abusos/1 or /abusos/1.json
  def destroy
    @abuso.destroy

    respond_to do |format|
      format.html { redirect_to abusos_url, notice: "Abuso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abuso
      @abuso = Abuso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def abuso_params
      params.require(:abuso).permit(:cliente, :fecha, :unidad, :tipo_contrato, :operador, :tipo_abuso, :abuso_presentado, :costo_total, :reporta)
    end
end

app/helpers/abusos_helper.rb
module AbusosHelper
end

app/views/abusos/_abuso.html.erb
<div id="<%= dom_id abuso %>">
  <p>
    <strong>Cliente:</strong>
    <%= abuso.cliente %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= abuso.fecha %>
  </p>

  <p>
    <strong>Unidad:</strong>
    <%= abuso.unidad %>
  </p>

  <p>
    <strong>Tipo contrato:</strong>
    <%= abuso.tipo_contrato %>
  </p>

  <p>
    <strong>Operador:</strong>
    <%= abuso.operador %>
  </p>

  <p>
    <strong>Tipo abuso:</strong>
    <%= abuso.tipo_abuso %>
  </p>

  <p>
    <strong>Abuso presentado:</strong>
    <%= abuso.abuso_presentado %>
  </p>

  <p>
    <strong>Costo total:</strong>
    <%= abuso.costo_total %>
  </p>

  <p>
    <strong>Reporta:</strong>
    <%= abuso.reporta %>
  </p>

</div>

app/views/abusos/_form.html.erb
<%= form_with(model: abuso) do |form| %>
  <% if abuso.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(abuso.errors.count, "error") %> prohibited this abuso from being saved:</h2>

      <ul>
        <% abuso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente, style: "display: block" %>
    <%= form.text_field :cliente %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.datetime_field :fecha %>
  </div>

  <div>
    <%= form.label :unidad, style: "display: block" %>
    <%= form.text_field :unidad %>
  </div>

  <div>
    <%= form.label :tipo_contrato, style: "display: block" %>
    <%= form.number_field :tipo_contrato %>
  </div>

  <div>
    <%= form.label :operador, style: "display: block" %>
    <%= form.text_field :operador %>
  </div>

  <div>
    <%= form.label :tipo_abuso, style: "display: block" %>
    <%= form.number_field :tipo_abuso %>
  </div>

  <div>
    <%= form.label :abuso_presentado, style: "display: block" %>
    <%= form.text_area :abuso_presentado %>
  </div>

  <div>
    <%= form.label :costo_total, style: "display: block" %>
    <%= form.text_field :costo_total %>
  </div>

  <div>
    <%= form.label :reporta, style: "display: block" %>
    <%= form.number_field :reporta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/abusos/edit.html.erb
<h1>Editing abuso</h1>

<%= render "form", abuso: @abuso %>

<br>

<div>
  <%= link_to "Show this abuso", @abuso %> |
  <%= link_to "Back to abusos", abusos_path %>
</div>

app/views/abusos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Abusos</h1>

<div id="abusos">
  <% @abusos.each do |abuso| %>
    <%= render abuso %>
    <p>
      <%= link_to "Show this abuso", abuso %>
    </p>
  <% end %>
</div>

<%= link_to "New abuso", new_abuso_path %>

app/views/abusos/new.html.erb
<h1>New abuso</h1>

<%= render "form", abuso: @abuso %>

<br>

<div>
  <%= link_to "Back to abusos", abusos_path %>
</div>

app/views/abusos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @abuso %>

<div>
  <%= link_to "Edit this abuso", edit_abuso_path(@abuso) %> |
  <%= link_to "Back to abusos", abusos_path %>

  <%= button_to "Destroy this abuso", @abuso, method: :delete %>
</div>