config/routes.rb
Rails.application.routes.draw do
  resources :reporte_abusos
  resources :contratos
  resources :folio_abusos
  resources :abusos

  root "folio_abusos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/folio_abuso.rb
class FolioAbuso < ApplicationRecord
end

app/controllers/folio_abusos_controller.rb
class FolioAbusosController < ApplicationController
  before_action :set_folio_abuso, only: %i[ show edit update destroy ]

  # GET /folio_abusos or /folio_abusos.json
  def index
    @folio_abusos = FolioAbuso.all.order("id desc")
    if params["filtro"].present?
      @folio_abusos = @folio_abusos.where("cliente LIKE ? OR folio LIKE ?", "%#{params["filtro"]}%", "%#{params["filtro"]}%")
    end
    @folio_abusos = @folio_abusos.paginate(page: params[:page], per_page: 10)
  end

  # GET /folio_abusos/1 or /folio_abusos/1.json
  def show
    el_folio_abuso = FolioAbuso.find_by_id(params["id"])
    @el_contrato = ["No encontrado"]
    @el_abuso = ["No encontrado"]
    if el_folio_abuso.present?
      @el_contrato = [Contrato.find_by_id(el_folio_abuso.tipo_contrato)]
    end
    if el_folio_abuso.present?
      @el_abuso = [ReporteAbuso.find_by_id(el_folio_abuso.tipo_abuso)]
    end

    puts "el abuso es"
    puts @el_contrato
    puts @el_abuso
  end

  # GET /folio_abusos/new
  def new
    @folio_abuso = FolioAbuso.new
    @contratos = Contrato.all
    @abusos = ReporteAbuso.all
  end

  # GET /folio_abusos/1/edit
  def edit
    #@folio_abuso = FolioAbuso.new
    @contratos = Contrato.all
    @abusos = ReporteAbuso.all
  end

  # POST /folio_abusos or /folio_abusos.json
  def create
    @folio_abuso = FolioAbuso.new(folio_abuso_params)

    respond_to do |format|
      if @folio_abuso.save
        @folio_abuso.folio = "#{'0'*(5-(@folio_abuso.id.to_s.size.to_i))}#{@folio_abuso.id}-#{Time.now.to_i}"
        @folio_abuso.save
        format.html { redirect_to folio_abuso_url(@folio_abuso), notice: "El folio se creo correctamente" }
        format.json { render :show, status: :created, location: @folio_abuso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @folio_abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folio_abusos/1 or /folio_abusos/1.json
  def update
    respond_to do |format|
      if @folio_abuso.update(folio_abuso_params)
        format.html { redirect_to folio_abuso_url(@folio_abuso), notice: "Folio actualizado" }
        format.json { render :show, status: :ok, location: @folio_abuso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @folio_abuso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folio_abusos/1 or /folio_abusos/1.json
  def destroy
    @folio_abuso.destroy

    respond_to do |format|
      format.html { redirect_to folio_abuso_url, notice: "Folio eliminado" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folio_abuso
      @folio_abuso = FolioAbuso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folio_abuso_params
      params.require(:folio_abuso).permit(:folio, :cliente, :fecha, :unidad, :tipo_contrato, :operador, :tipo_abuso, :abuso_presentado, :costo_total, :reporta)
    end
end

app/helpers/folio_abusos_helper.rb
module FolioAbusosHelper
end

app/views/folio_abusos/_folio_abuso.html.erb
<div class="container">
  <h1>Folio: <%= @folio_abuso.folio %> </h1>
  <%= form_with(model: folio_abuso) do |form| %>
    <div class="row">
        <div class="form-group col-sm">
          <%= form.label :cliente, style: "display: block" %>
          <%= form.text_field :cliente, class:"form-control", readonly:true %>
        </div>


        <div class="form-group col-sm">
          <%= form.label :fecha, style: "display: block" %>
          <%= form.datetime_field :fecha, class:"form-control", readonly:true %>
        </div>
      </div>

      <div class="row">


        <div class="form-group col-sm">
          <%= form.label :unidad, style: "display: block" %>
          <%= form.text_field :unidad, class:"form-control", readonly:true %>
        </div>

        <div class="form-group col-sm">
          <%= form.label :tipo_contrato, style: "display: block" %>
          <% options = options_from_collection_for_select(@el_contrato, 'id', 'tipo_contrato') %>
          <%= form.select :tipo_contrato,  options, class:"form-select"  %>
        </div>

      </div>

      <div class="row">
        <div class="form-group col-sm">
          <%= form.label :operador, style: "display: block" %>
          <%= form.text_field :operador, class:"form-control", readonly:true %>
        </div>

        <div class="form-group col-sm">
          <%= form.label :tipo_abuso, style: "display: block" %>
          <% options = options_from_collection_for_select(@el_abuso, 'id', 'tipo_abuso') %>
        <%= form.select :tipo_abuso,  options, class:"form-select"  %>
        </div>

      </div>

      <div class="row">
        <div class="form-group col-sm">
          <%= form.label :abuso_presentado, style: "display: block" %>
          <%= form.text_area :abuso_presentado, class:"form-control", readonly:true %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-sm">
          <%= form.label :costo_total, style: "display: block" %>
          <%= form.text_field :costo_total, class:"form-control", readonly:true %>
        </div>

        <div class="form-group col-sm">
          <%= form.label :reporta, style: "display: block" %>
          <%= form.text_field :reporta, class:"form-control", readonly:true %>
        </div>
      </div>

      <div class="actions">
          <%= link_to "Regresar", folio_abusos_path, class:"btn btn-light min-width-btn" %>
        <%= link_to 'Editar', edit_folio_abuso_path(@folio_abuso), class:"btn btn-primary min-width-btn"  %>     
        <%= link_to 'Eliminar', @folio_abuso , method: :delete, data: { confirm: 'Estas seguro?' }, class:"btn btn-danger min-width-btn"%>
      </div>
    <% end %>
</div>

app/views/folio_abusos/_form.html.erb
<div class="container">
  <br>
  <br>
  <%= form_with(model: folio_abuso) do |form| %>
    <% if folio_abuso.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h5><%= pluralize(folio_abuso.errors.count, "error") %> prohibited this folio_abuso from being saved:</h5>

        <ul>
          <% folio_abuso.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.text_field :cliente, class:"form-control", id:"floatingInput", placeholder:"name@example.com" %>
          <label for="floatingInput">Cliente</label>
        </div>
      </div>

      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.datetime_field :fecha, class:"form-control", id:"fechaid" %>
          <label for="fechaid">Fecha</label>
        </div>
      </div>
    </div>

    <div class="row">


      <div class="form-group col-sm">

         <div class="form-floating">
          <%= form.text_field :unidad, class:"form-control", id:"unidadid", placeholder:"Nissan" %>
          <label for="unidadid">Unidad</label>
        </div>
      </div>

      <div class="form-group col-sm">
        <%= form.label :tipo_contrato, style: "display: block" %>
        <% options = options_from_collection_for_select(@contratos, 'id', 'tipo_contrato') %>
        <%= form.select :tipo_contrato,  options, class:"form-control"  %>
      </div>

    </div>

    <div class="row">
      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.text_field :operador, class:"form-control", id:"operadorid", placeholder:"Charlie" %>
          <label for="operadorid">Operador</label>
        </div>
      </div>

      <div class="form-group col-sm">
        <%= form.label :tipo_abuso, style: "display: block" %>
        <% options = options_from_collection_for_select(@abusos, 'id', 'tipo_abuso') %>
        <%= form.select :tipo_abuso,  options, class:"form-select form-select-lg mb-3"  %>
      </div>

    </div>

    <div class="row">
      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.text_area :abuso_presentado, class:"form-control", id:"abuso_presentadoid", placeholder:"Charlie" %>
          <label for="abuso_presentadoid">Informe</label>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.text_field :costo_total, class:"form-control", id:"costo_totalid", placeholder:"Charlie" %>
          <label for="costo_totalid">Costo total</label>
        </div>
      </div>

      <div class="form-group col-sm">
        <div class="form-floating">
          <%= form.text_field :reporta, class:"form-control", id:"reportaid", placeholder:"Charlie" %>
          <label for="reportaid">Reporta</label>
        </div>
      </div>
    </div>

    <br>
    <div class="actions">
      <%= form.submit "Registrar", class: 'btn btn-success btn-lg btn-block' %>
    </div>
  <% end %>

</div>

app/views/folio_abusos/edit.html.erb
<div class="container-fluid">
  <center>
    <h1>Editar Folio <%= @folio_abuso.folio%> </h1>
  </center>
    

  <%= render "form", folio_abuso: @folio_abuso %>

  <br>

  <div>
    <%= link_to "Mostrar Folio", @folio_abuso %> |
    <%= link_to "Regresar al menu anterior", folio_abusos_path %>
  </div>
</div>

app/views/folio_abusos/index.html.erb
<div class="container-xl">
  <br>
  <br>
  <h3>
  Nombre de la empresa
  <small class="text-muted">Folios</small>
</h3>
  <br>

  <div class="container-xl">
    <div class="row align-items-start">
      <div class="col">
        <%= link_to "Registar nuevo Folio", new_folio_abuso_path, class:"btn btn-info" %>
      </div>
      <div class="col">
        <%= form_for :folio_abuso, method: :get do |f| %>  
          <input type="text" name="filtro" id="filtro" value="" placeholder="Buscar" bind="query" class="form-control">
        <% end %>
      </div>
      <div class="col">
        <button class="btn btn-warning">Buscar</button>
      </div>
    </div>
  </div>
  <br>
  <div id="folio_abusos">
    <table class="table table-success table-striped table-hover table-borderless">
      <thead>
        <tr>
          <th scope="col">No. Folio</th>
          <th scope="col">Cliente</th>
          <th scope="col">Fecha</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @folio_abusos.each do |folio_abuso| %>
          <tr>
            <th scope="row"><%= folio_abuso.folio %> </th>
            <td><%= folio_abuso.cliente %></td>
            <td><%= folio_abuso.fecha %></td>
            <td>
              <!-- Example single danger button -->
              <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  Accion
                </button>
                <ul class="dropdown-menu">
                  <%= link_to 'Ver', folio_abuso, class:"dropdown-item" %>
                  <li><a class="dropdown-item" href="<%= edit_folio_abuso_path(folio_abuso) %>">Editar</a></li>
                  <%= link_to 'Eliminar', folio_abuso , method: :delete, data: { confirm: 'Estas seguro?' }, class:"dropdown-item"%>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @folio_abusos %>
  </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <img src="..." class="rounded me-2" alt="...">
      <strong class="me-auto">Bootstrap</strong>
      <small>11 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      Hello, world! This is a toast message.
    </div>
  </div>
</div>

app/views/folio_abusos/new.html.erb
<br>
<div class="container-fluid">
  <br>
  <center>
    <h1>Registrar nuevo Incidente</h1>
  </center>
  
  <br>
  <%= render "form", folio_abuso: @folio_abuso %>

  <br>
  <br>

  <div>
    <%= link_to "Regresar a Folios", folio_abusos_path %>
  </div>

</div>

app/views/folio_abusos/show.html.erb
<div class="alert alert-success" role="alert">
  <p><%= notice %></p>
</div>
<%= render @folio_abuso %>

<div>

</div>