config/routes.rb
Rails.application.routes.draw do
  resources :reporte_abusos
  resources :contratos
  resources :folio_abusos
  resources :abusos

  root "folio_abusos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/contrato.rb
class Contrato < ApplicationRecord
end

app/controllers/contratos_controller.rb
class ContratosController < ApplicationController
  before_action :set_contrato, only: %i[ show edit update destroy ]

  # GET /contratos or /contratos.json
  def index
    @contratos = Contrato.all
  end

  # GET /contratos/1 or /contratos/1.json
  def show
  end

  # GET /contratos/new
  def new
    @contrato = Contrato.new
  end

  # GET /contratos/1/edit
  def edit
  end

  # POST /contratos or /contratos.json
  def create
    @contrato = Contrato.new(contrato_params)

    respond_to do |format|
      if @contrato.save
        format.html { redirect_to contrato_url(@contrato), notice: "Contrato was successfully created." }
        format.json { render :show, status: :created, location: @contrato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contratos/1 or /contratos/1.json
  def update
    respond_to do |format|
      if @contrato.update(contrato_params)
        format.html { redirect_to contrato_url(@contrato), notice: "Contrato was successfully updated." }
        format.json { render :show, status: :ok, location: @contrato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contratos/1 or /contratos/1.json
  def destroy
    @contrato.destroy

    respond_to do |format|
      format.html { redirect_to contratos_url, notice: "Contrato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contrato
      @contrato = Contrato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contrato_params
      params.require(:contrato).permit(:tipo_contrato, :descripcion)
    end
end

app/helpers/contratos_helper.rb
module ContratosHelper
end

app/views/contratos/_contrato.html.erb
<div id="<%= dom_id contrato %>">
  <p>
    <strong>Tipo contrato:</strong>
    <%= contrato.tipo_contrato %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= contrato.descripcion %>
  </p>

</div>

app/views/contratos/_form.html.erb
<%= form_with(model: contrato) do |form| %>
  <% if contrato.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contrato.errors.count, "error") %> prohibited this contrato from being saved:</h2>

      <ul>
        <% contrato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tipo_contrato, style: "display: block" %>
    <%= form.text_field :tipo_contrato %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contratos/edit.html.erb
<h1>Editing contrato</h1>

<%= render "form", contrato: @contrato %>

<br>

<div>
  <%= link_to "Show this contrato", @contrato %> |
  <%= link_to "Back to contratos", contratos_path %>
</div>

app/views/contratos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contratos</h1>

<div id="contratos">
  <% @contratos.each do |contrato| %>
    <%= render contrato %>
    <p>
      <%= link_to "Show this contrato", contrato %>
    </p>
  <% end %>
</div>

<%= link_to "New contrato", new_contrato_path %>

app/views/contratos/new.html.erb
<h1>New contrato</h1>

<%= render "form", contrato: @contrato %>

<br>

<div>
  <%= link_to "Back to contratos", contratos_path %>
</div>

app/views/contratos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contrato %>

<div>
  <%= link_to "Edit this contrato", edit_contrato_path(@contrato) %> |
  <%= link_to "Back to contratos", contratos_path %>

  <%= button_to "Destroy this contrato", @contrato, method: :delete %>
</div>